title: General City Layers
mapboxAccessToken: pk.eyJ1IjoiZ2djaXR5IiwiYSI6ImNqNXpjM3czcjA4djIzMm4wOWQ0YjExMzcifQ.PeDOEiLNe7AkmhSa9ZK3aQ

mapOptions:
  minZoom: 11
  maxZoom: 22
  bounds:
    - -118.019772
    - 33.810159
    - -117.920122
    - 33.727172
  attributionPrefix: City of Garden Grove

widgets:
  - Select:
      customPopupTemplate: /demos/configs/city-popup.js
      layers: 
        city.public_addresses: 'Addresses'
        parcels: 'Parcels'
      excludedLayers:
        - zoning
      operations:
        - land: true
        - bufferSelect:
            selectOnly: parcels-polygons
        - publicNotice:
            url: https://foo.com
  - Basemaps
  - ToC
  - Print
  - Share
  - Measure
  - Nearmap:
      style: /demos/data-sources/nearmap.json

basemaps:
  - name: Default
    style: https://ggcity.org/tileserver/styles/standard/style.json
    attributions: '&copy; City of Garden Grove, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    imagePreview: /demos/assets/default.png
  - name: OSM Bright
    style: mapbox://styles/ggcity/ckfo8an0k02ay19p10zg06oat
    attributions: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    imagePreview: /demos/assets/osm-bright.png

vectorOverlay: /demos/data-sources/city.json

imageOverlay:
  url: https://ggcity.org/geoserver/gis/wms
  serverType: geoserver
  params:
    layers: gis:city.council_district_info